#### Base

In [14]:
import pandas as pd
import numpy as np
import os

directory = os.getcwd()

os.chdir(directory)

In [15]:
path_file = 'MegaSena.xlsx'

df = pd.read_excel(path_file, sheet_name='megasena', header=0)

In [16]:
df.columns

Index(['Concurso', 'Data', 'bola 1', 'bola 2', 'bola 3', 'bola 4', 'bola 5',
       'bola 6'],
      dtype='object')

In [17]:
df = df[['Concurso', 'Data', 'bola 1', 'bola 2', 'bola 3', 'bola 4', 'bola 5', 'bola 6']]

#### Analise Números Sorteados Mega Sena

In [18]:
array_jogos = np.array(df[['bola 1', 'bola 2', 'bola 3', 'bola 4', 'bola 5', 'bola 6']])

In [30]:
# Values counts de cada número sorteado.
valores, contagem = np.unique(array_jogos, return_counts=True)
frequencia_numeros = dict(zip(valores, contagem))
df_frequencia = pd.DataFrame(list(frequencia_numeros.items()), columns=['Número', 'Frequência']).sort_values(by='Frequência', ascending=False).reset_index(drop=True)
# Salvar em CSV
df_frequencia.to_csv('frequencia_numeros_sorteados.csv', index=False)

In [29]:
display(df_frequencia)

    Número  Frequência
0       10         347
1       53         338
2       37         322
3        5         322
4       34         321
5       33         318
6       38         317
7        4         314
8       30         313
9       32         313
10      17         313
11      27         312
12      35         312
13      56         312
14      44         312
15      42         312
16      11         311
17      46         310
18      54         310
19      43         309
20      23         309
21      13         307
22      16         306
23      41         306
24      28         304
25      51         301
26      49         301
27      36         300
28      52         299
29      24         297
30       6         296
31      29         295
32       2         295
33      25         294
34       8         293
35      50         290
36      45         290
37      20         289
38      19         288
39       1         288
40      14         288
41      59         287
42      60         285
43       9         284
44      39         284
45      57         284
46      47         283
47      18         283
48      58         282
49      40         279
50      12         279
51       7         277
52      48         277
53       3         275
54      31         274
55      15         266
56      22         263
57      55         256
58      21         248
59      26         244

#### Analise Números Escolhidos

In [21]:
df_num_escolhidos = pd.read_csv('numeros_escolhidos.csv', sep=';', header=None)
array_jogos_esc = np.array(df_num_escolhidos)

array_jogos_esc

array([[10, 13, 18, 36, 48, 59],
       [ 7,  9, 13, 29, 36, 49],
       [ 4,  5, 19, 21, 48, 54],
       [11, 25, 31, 44, 50, 55],
       [12, 13, 16, 23, 30, 37],
       [ 1,  5,  9, 10, 18, 27],
       [ 5, 19, 22, 31, 48, 54],
       [10, 16, 37, 48, 56, 57],
       [ 5,  9, 12, 22, 35, 43],
       [12, 23, 38, 44, 52, 57],
       [ 6, 12, 20, 45, 48, 58],
       [ 0,  0,  0,  0,  0, 39]])

In [33]:
# Values counts de cada número sorteado.
valores_esc, contagem_esc = np.unique(array_jogos_esc, return_counts=True)
frequencia_numeros_esc = dict(zip(valores_esc, contagem_esc))
df_frequencia_esc = pd.DataFrame(list(frequencia_numeros_esc.items()), columns=['Número', 'Frequência'])
df_frequencia_esc = df_frequencia_esc[1:].sort_values(by='Frequência', ascending=False).reset_index(drop=True)
# Salvar em CSV
df_frequencia_esc.to_csv('frequencia_numeros_escolhidos.csv', index=False)

In [35]:
display(df_frequencia_esc)

    Número  Frequência
0       48           5
1        5           4
2       12           4
3        9           3
4       10           3
5       13           3
6       16           2
7       19           2
8       36           2
9       44           2
10      37           2
11      57           2
12      54           2
13      22           2
14      31           2
15      18           2
16      23           2
17      11           1
18       4           1
19       6           1
20       1           1
21       7           1
22      21           1
23      20           1
24      35           1
25      30           1
26      27           1
27      29           1
28      25           1
29      39           1
30      43           1
31      38           1
32      49           1
33      45           1
34      52           1
35      50           1
36      55           1
37      56           1
38      58           1
39      59           1